
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:17 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.1/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:17 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "C:/Users/Brian/AppData/Local/cloud-code/installer/google-cloud-sdk/bin/"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "C:/ProgramData/chocolatey/bin/"
      - "C:/Python311/Scripts/"
      - "C:/Python311/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "C:/Program Files/PuTTY/"
      - "C:/Program Files/Tailscale/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Program Files/Nordic Semiconductor/nrf-command-line-tools/bin/"
      - "C:/Program Files/Go/bin/"
      - "C:/Program Files/OpenSSL-Win64/bin/"
      - "C:/Users/Brian/esp/v5.5.1/esp-idf/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/Docker/Docker/resources/bin/"
      - "C:/Users/Brian/xpack-openocd-0.12.0-7-win32-x64/xpack-openocd-0.12.0-7/bin/"
      - "C:/Users/Brian/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/Brian/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Users/Brian/AppData/Local/particle/bin/"
      - "C:/Users/Brian/AppData/Local/Programs/cursor/resources/app/bin/"
      - "C:/Users/Brian/go/bin/"
      - "C:/Users/Brian/AppData/Roaming/Python/Python311/Scripts/"
      - "C:/Program Files/Ninja/"
      - "C:/Program Files (x86)/GNU Arm Embedded Toolchain/12 2022-q4-major/bin/"
      - "C:/Users/Brian/.vscode/extensions/ms-python.debugpy-2025.18.0-win32-x64/bundled/scripts/noConfigScripts/"
    searched_directories:
      - "C:/Users/Brian/AppData/Local/cloud-code/installer/google-cloud-sdk/bin/ninja-build.com"
      - "C:/Users/Brian/AppData/Local/cloud-code/installer/google-cloud-sdk/bin/ninja-build.exe"
      - "C:/Users/Brian/AppData/Local/cloud-code/installer/google-cloud-sdk/bin/ninja-build"
      - "C:/Users/Brian/AppData/Local/cloud-code/installer/google-cloud-sdk/bin/ninja.com"
      - "C:/Users/Brian/AppData/Local/cloud-code/installer/google-cloud-sdk/bin/ninja.exe"
      - "C:/Users/Brian/AppData/Local/cloud-code/installer/google-cloud-sdk/bin/ninja"
      - "C:/Users/Brian/AppData/Local/cloud-code/installer/google-cloud-sdk/bin/samu.com"
      - "C:/Users/Brian/AppData/Local/cloud-code/installer/google-cloud-sdk/bin/samu.exe"
      - "C:/Users/Brian/AppData/Local/cloud-code/installer/google-cloud-sdk/bin/samu"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja-build.com"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja-build.exe"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja-build"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja.com"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja.exe"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/samu.com"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/samu.exe"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/samu"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja-build.com"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja-build.exe"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja-build"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja.com"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja.exe"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/samu.com"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/samu.exe"
      - "C:/Users/Brian/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/samu"
      - "C:/ProgramData/chocolatey/bin/ninja-build.com"
      - "C:/ProgramData/chocolatey/bin/ninja-build.exe"
      - "C:/ProgramData/chocolatey/bin/ninja-build"
      - "C:/ProgramData/chocolatey/bin/ninja.com"
    found: "C:/ProgramData/chocolatey/bin/ninja.exe"
    search_context:
      ENV{PATH}:
        - "C:\\Users\\Brian\\AppData\\Local\\cloud-code\\installer\\google-cloud-sdk\\bin"
        - "c:\\Users\\Brian\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\debugCommand"
        - "c:\\Users\\Brian\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\copilotCli"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "C:\\Python311\\Scripts\\"
        - "C:\\Python311\\"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NvDLISR"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\PuTTY\\"
        - "C:\\Program Files\\Tailscale\\"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\Nordic Semiconductor\\nrf-command-line-tools\\bin\\"
        - "C:\\Program Files\\Go\\bin"
        - "C:\\Program Files\\OpenSSL-Win64\\bin"
        - "C:\\Users\\Brian\\esp\\v5.5.1\\esp-idf"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "C:\\Users\\Brian\\xpack-openocd-0.12.0-7-win32-x64\\xpack-openocd-0.12.0-7\\bin"
        - "C:\\Users\\Brian\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\Brian\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\Brian\\AppData\\Local\\particle\\bin"
        - "C:\\Users\\Brian\\AppData\\Local\\Programs\\cursor\\resources\\app\\bin"
        - "C:\\Users\\Brian\\go\\bin"
        - "C:\\Users\\Brian\\AppData\\Roaming\\Python\\Python311\\Scripts"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\Ninja"
        - "C:\\Program Files (x86)\\GNU Arm Embedded Toolchain\\12 2022-q4-major\\bin"
        - "c:\\Users\\Brian\\.vscode\\extensions\\ms-python.debugpy-2025.18.0-win32-x64\\bundled\\scripts\\noConfigScripts"
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.1/Modules/FindPython/Support.cmake:2430 (find_program)"
      - "C:/Program Files/CMake/share/cmake-4.1/Modules/FindPython3.cmake:656 (include)"
      - "C:/Users/Brian/pouch_gateway_clean/zephyr/cmake/modules/python.cmake:41 (find_package)"
      - "C:/Users/Brian/pouch_gateway_clean/zephyr/cmake/modules/user_cache.cmake:30 (include)"
      - "C:/Users/Brian/pouch_gateway_clean/zephyr/cmake/modules/extensions.cmake:5 (include)"
      - "cmake/modules/sysbuild_default.cmake:8 (include)"
      - "C:/Users/Brian/pouch_gateway_clean/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:75 (include)"
      - "C:/Users/Brian/pouch_gateway_clean/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "C:/Users/Brian/pouch_gateway_clean/zephyr/share/sysbuild-package/cmake/SysbuildConfig.cmake:8 (include)"
      - "template/CMakeLists.txt:10 (find_package)"
    mode: "program"
    variable: "_Python3_EXECUTABLE_DEBUG"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "python3.11_d"
      - "python3_d"
      - "python_d"
    candidate_directories:
      - "C:/Python311/"
    searched_directories:
      - "C:/Python311/python3.11_d.com"
      - "C:/Python311/python3.11_d.exe"
      - "C:/Python311/python3.11_d"
      - "C:/Python311/python3_d.com"
      - "C:/Python311/python3_d.exe"
      - "C:/Python311/python3_d"
      - "C:/Python311/python_d.com"
      - "C:/Python311/python_d.exe"
      - "C:/Python311/python_d"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\Users\\Brian\\AppData\\Local\\cloud-code\\installer\\google-cloud-sdk\\bin"
        - "c:\\Users\\Brian\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\debugCommand"
        - "c:\\Users\\Brian\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\copilotCli"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "C:\\Python311\\Scripts\\"
        - "C:\\Python311\\"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NvDLISR"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\PuTTY\\"
        - "C:\\Program Files\\Tailscale\\"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\Nordic Semiconductor\\nrf-command-line-tools\\bin\\"
        - "C:\\Program Files\\Go\\bin"
        - "C:\\Program Files\\OpenSSL-Win64\\bin"
        - "C:\\Users\\Brian\\esp\\v5.5.1\\esp-idf"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "C:\\Users\\Brian\\xpack-openocd-0.12.0-7-win32-x64\\xpack-openocd-0.12.0-7\\bin"
        - "C:\\Users\\Brian\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\Brian\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\Brian\\AppData\\Local\\particle\\bin"
        - "C:\\Users\\Brian\\AppData\\Local\\Programs\\cursor\\resources\\app\\bin"
        - "C:\\Users\\Brian\\go\\bin"
        - "C:\\Users\\Brian\\AppData\\Roaming\\Python\\Python311\\Scripts"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\Ninja"
        - "C:\\Program Files (x86)\\GNU Arm Embedded Toolchain\\12 2022-q4-major\\bin"
        - "c:\\Users\\Brian\\.vscode\\extensions\\ms-python.debugpy-2025.18.0-win32-x64\\bundled\\scripts\\noConfigScripts"
      CMAKE_INSTALL_PREFIX: "C:/Program Files (x86)/sysbuild_toplevel"
      CMAKE_SYSTEM_PREFIX_PATH:
        - "C:/Program Files"
        - "C:/Program Files (x86)"
        - "C:/Program Files/CMake"
        - "C:/Program Files (x86)/sysbuild_toplevel"
...
